apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: frontend
        app: dice
    spec:
      containers:
      - name: frontend
        image: khurram88/frontend-app
        ports:
        - containerPort: 8080
          name: tcp
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    tier: frontend
    app: dice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000